// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZbYzRTyXXXY-ebukwWTWBZz7_cQFHMUk',
    appId: '1:337840326077:android:8fa072e0955bd10d92fed4',
    messagingSenderId: '337840326077',
    projectId: 'partypay-91ee9',
    databaseURL: 'https://partypay-91ee9-default-rtdb.firebaseio.com',
    storageBucket: 'partypay-91ee9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgfAzaTyXj3-lFdk1LAY4BuY9KncMDxNs',
    appId: '1:337840326077:ios:640830c9e1ae7bef92fed4',
    messagingSenderId: '337840326077',
    projectId: 'partypay-91ee9',
    databaseURL: 'https://partypay-91ee9-default-rtdb.firebaseio.com',
    storageBucket: 'partypay-91ee9.appspot.com',
    androidClientId: '337840326077-49ojlo178p31jsanq1br4sfgj604flp8.apps.googleusercontent.com',
    iosClientId: '337840326077-k9t23u282vk2nff2enjv6ilga4gdb976.apps.googleusercontent.com',
    iosBundleId: 'br.com.fairie.partypay',
  );
}
